### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by rohithkodali** [vishalshar/SpeakerDiarization_RNN#1]
HI VIshal,

    Your paper seems interesting and i want to see it in action with some sample test files, can you please send them to my email rohitkodali@gmail.com

**Comment by vishalshar** [comment]
Hi Rohit,

Thank you for your interest in our work. 
We still currently working on it and it is not published yet. At this point in time, I cannot share code. 

To have a glimpse of performance, you can look at results in the document (at the end).
